---
title: "Задание 4"
author: "Sergey"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```
## Модель пациента: вероятность выздоровления

```{r probability, patients & repeats, echo=FALSE}
true_prob <- 0.3 # Истинная вероятность выздоровления
n_patients <- 100 # Объем выборки (количество пациентов)
n_repeats <- 1000 # Количество повторений эксперимента

#values <- 0:32 # Значения, которые может принимать прирост (случайная величина)
#max_val <- max(values) # Максимальное значение случайной величины
#Pr <- 1/length(values)  # Распределение в генеральной совокупности

#df <- data.frame(values, Pr)

#ggplot(df, aes(x=values, y=Pr)) +
  #geom_point() + 
  #geom_segment( aes(x=values, xend=values, y=0, yend=Pr)) +
  #scale_x_continuous(breaks = values) +
  #theme_bw()

```

```{r characteristics, echo=FALSE}
#true_mean <- sum(values*Pr) # Истинное среднее (математическое ожидание)
#print(true_mean)
#variance <- sum((values-true_mean)^2*Pr) # Дисперсия
#print(variance)
#standard_deviation <- sqrt(variance)
#print(standard_deviation)
```
# Функция для проведения эксперимента с заданной вероятностью выздоровления

```{r function and sample assembly}
#n_patients <- 500 # Количество добровольцев 
#my_group_Hg_upd <- round(runif(n_patients, 0, max_val), 0) # Результаты добровольцев
#print(my_group_Hg_upd)
#sample_mean <- mean(my_group_Hg_upd)
#print(sample_mean)

run_experiment <- function(n_patients, true_prob, n_repeats) {
  df_all_repeats <- data.frame(
    n_exp = rep(1:n_repeats, each = n_patients),
    ID =  rep(1:n_patients, n_repeats),
    recovery = rbinom(n_repeats * n_patients, 1, true_prob) # Случайное событие (1 - выздоровление, 0 - нет)
  )
  
  df_sample_prob <- df_all_repeats %>%
    group_by(n_exp) %>%
    summarise(sample_prob = mean(recovery)) %>% # Средняя вероятность в каждом эксперименте
    ungroup()
  
  return(df_sample_prob)
}
```
# Проведение эксперимента

```{r run function}
#n_patients <- 500 # Количество добровольцев 
#n_repeats <- 1000 # Количество повторений эксперимента

#df_all_repeats <- data.frame(
  #n_exp = rep(1:n_repeats, each = n_patients),
  #ID =  rep(1:n_patients, n_repeats),
  #Hg_upd = round(runif(n_repeats*n_patients, 0, max_val), 0))
#df_all_repeats
df_sample_prob <- run_experiment(n_patients, true_prob, n_repeats)
df_sample_prob
```
# Гистограмма оценок вероятности выздоровления

```{r histogram}
#df_sample_mean <- df_all_repeats %>% 
  #group_by(n_exp) %>% 
  #dplyr::summarise(mean_Hg_upd = mean(Hg_upd)) %>% 
  #ungroup()
#ggplot(df_sample_mean, aes(x = mean_Hg_upd)) +
  #geom_histogram(color = 'black', fill = 'white', binwidth = 0.1) +
  #theme_bw()

ggplot(df_sample_prob, aes(x = sample_prob)) +
  geom_histogram(color = 'black', fill = 'white', binwidth = 0.01) +
  geom_vline(xintercept = true_prob, color = 'red', linetype = "dashed") + # Истинная вероятность
  theme_bw() +
  ggtitle("Распределение оценок вероятности выздоровления")
```
# Ошибка (RMSE) между истинной вероятностью и оценками

```{r RMSE}
#error <- sqrt( mean((df_sample_mean$mean_Hg_upd-true_mean)^2) )
#print(error)

error <- sqrt(mean((df_sample_prob$sample_prob - true_prob)^2))
print(paste("Среднеквадратичная ошибка (RMSE):", round(error, 4)))
```
# Зависимость ошибки от объема выборки

```{r, RMSE size and sample size}
sample_sizes <- seq(10, 1000, by = 50) # Разные объемы выборок
errors <- data.frame(sample_size = sample_sizes, RMSE = rep(0, length(sample_sizes)))

for (i in seq_along(sample_sizes)) {
  n_patients <- sample_sizes[i]
  df_sample_prob <- run_experiment(n_patients, true_prob, n_repeats)
  errors$RMSE[i] <- sqrt(mean((df_sample_prob$sample_prob - true_prob)^2))
}

```
# График зависимости RMSE от объема выборки

```{r, plot}
ggplot(errors, aes(x = sample_size, y = RMSE)) +
  geom_line() +
  geom_point() +
  theme_bw() +
  ggtitle("Зависимость RMSE от объема выборки")
```

