---
title: "Управление данными (статистическое программирование)"
author: "Sergey"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(writexl)
```

# Управление данными (статистическое программирование)

## Подгрузка датасетов

```{r}
data <- read_excel("ADaM-like/ADSL.xlsx")
data_MH <- read_excel("SDTM/MH_MEDICALHISTORY.xlsx")
```

## Преобразование датасетов

### ADSL
Датасет, содержащий данные субъектов
Трасмутом преобразуем переменные, если они не строковом формате

```{r}
data_join <- data %>% 
  transmute(
    STUDYID = as.character(STUDYID), 
    USUBJID = as.character(USUBJID),
    TRTP = as.character(TRTP),
    TRTPN = as.numeric(TRTPN) 
  )
```

### Mediacal history 
Содержит данные медицинской истории (MH) субъектов

```{r}
data_MH_join <- data_MH %>%
  # Отфильтровываем строки, где MHTERM не пусто, и категории равны "Medical History"
  filter(!is.na(MHTERM) & MHCAT == "Medical History") %>% 
  transmute(
    # Уникальный идентификатор субъекта
    USUBJID = paste(STUDYID, SUBJID, sep = '-'),
    # Порядковый номер
    MHSEQ = as.numeric(MHSEQ),
    # Категория медицинской истории
    MHCAT = as.character(MHCAT),
    # Отчетный термин для истории болезни
    MHTERM = as.character(MHTERM),
    # Дата/время начала приема препарата
    MHSTDTC = as.character(MHSTDTC),
    # Термин, выведенный в словаре (PT)
    MHDECOD = as.character(MHDECOD),
    # Система организма или класс органов (SOC)
    MHBODSYS = as.character(MHBODSYS),
    # Преобразование дат - форматированная дата начала и ее уровень точности
    # MHSTDTC → ASTDT и ASTDTF
    ASTDT = format(ymd(case_when(
      # Если MHENDTC имеет длину 7 символов (т.е. указаны год и месяц), добавляется "-01", чтобы получить полную дату
      nchar(MHSTDTC) == 7 ~ paste0(MHSTDTC, "-01"),
      # Если MHENDTC имеет длину 4 символа (т.е. указан только год), добавляется "-01-01", чтобы получить полную дату
      nchar(MHSTDTC) == 4 ~ paste0(MHSTDTC, "-01-01"), 
      # Если MHENDTC уже имеет полный формат даты
      TRUE ~ MHSTDTC
      )), "%d.%m.%Y"),
    ASTDTF = case_when(
      nchar(MHSTDTC) < 4 | is.na(MHSTDTC) ~ "Y", 
      nchar(MHSTDTC) == 4 ~ "M", 
      nchar(MHSTDTC) == 7 ~ "D",   
      TRUE ~ NA
      ),
    # Преобразование аналогично для даты окончания MHENDTC → AENDT и AENDTF
    MHENDTC = as.character(MHENDTC), 
    # Создаем переменную, содержащую отформатированную дату окончания события
    AENDT = case_when(
      TRUE ~ format(ymd(case_when(
      nchar(MHENDTC) == 7 ~ paste0(MHENDTC, "-01"), 
      nchar(MHENDTC) == 4 ~ paste0(MHENDTC, "-01-01"),
      TRUE ~ MHENDTC
      )), "%d.%m.%Y"),
      # Если значение MHENRTPT равно "ONGOING" - если исследование продолжается
      MHENRTPT == "ONGOING" ~ MHENRTPT),
    AENDTF = case_when(
      nchar(MHENDTC) < 4 | is.na(MHENDTC) ~ "Y", 
      nchar(MHENDTC) == 4 ~ "M", 
      nchar(MHENDTC) == 7 ~ "D",   
      TRUE ~ NA
      ),
    MHENRTPT = as.character(MHENRTPT), 
    MHENRF = case_when(
      MHENRTPT == "ONGOING" ~ MHENRTPT,
      TRUE ~ NA
    )
  ) 
```

## Сборка датасета ADMH

```{r}
ADMH <- left_join(data_join, data_MH_join, by = join_by(USUBJID))

write_xlsx(ADMH, "ADaM-like/ADMH.xlsx")
```

